spring.application.name=management

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${MYSQL_DATABASE:management}?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
spring.datasource.username=${MYSQL_USER:management}
spring.datasource.password=${MYSQL_PASSWORD:management}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.data.web.pageable.max-page-size=100
